import { Disclosure, PageHero, SectionHeading } from "../../components/PagePrimitives";
import { SiteIcon } from "../../components/SiteChrome";
import { supportSystems } from "../../data/investment";

export default function FounderSupportPage() {
  return <>
    <PageHero number="03" eyebrow="Founder support" title="Support shaped around the company." body="Odra brings capital, operating support, technology access, and an international network around founders at defining moments—when the fit and approved scope are right." image="/assets/odra-founder-collaboration.png" actions={[{ label: "Explore investment approach", href: "/investment" }, { label: "Start an application", href: "/apply" }]} />
    <section className="phase-section support-systems"><SectionHeading eyebrow="Three support systems" title="Useful by design. Specific by agreement." body="Every benefit is attached to the relevant pathway, company, provider terms, and current availability." /><div className="support-system-grid">{supportSystems.map((system) => <article className={`tone-${system.tone}`} key={system.number}><div><span>{system.number}</span><SiteIcon name={system.icon} /></div><h3>{system.title}</h3><p>{system.body}</p><small>{system.availability}</small></article>)}</div></section>
    <section className="phase-section support-boundaries"><div><p className="kicker">Clear boundaries</p><h2>No universal promises.<br />No decorative benefit totals.</h2></div><div className="support-rules"><article><span>01</span><h3>Eligibility is contextual</h3><p>Support depends on the company, pathway, agreement, availability, and provider rules.</p></article><article><span>02</span><h3>Values require a source</h3><p>Benefit amounts and “up to” claims stay hidden without current provider documentation.</p></article><article><span>03</span><h3>Participation is distinct</h3><p>School, Accelerator, or Scale participation does not necessarily mean Odra invested.</p></article></div></section>
    <section className="phase-section support-next"><SectionHeading eyebrow="The next defining milestone" title="Start with the route that matches where you are." /><div className="support-next-actions"><a href="/investment/focus">Review founder fit <SiteIcon name="arrow-right" /></a><a href="/portfolio">Meet the companies <SiteIcon name="arrow-right" /></a><a href="/apply">Apply to Odra <SiteIcon name="arrow-right" /></a></div><Disclosure>Support descriptions explain potential capability families. They are not contractual offers, guaranteed services, or approved partner-benefit claims.</Disclosure></section>
  </>;
}
