import { Disclosure, PageHero, SectionHeading } from "../../components/PagePrimitives";
import { focusAreas, founderFitSignals } from "../../data/investment";

export default function InvestmentFocusPage() {
  return <>
    <PageHero number="02" eyebrow="Investment focus" title="Technology with the potential to matter." body="Four equal-weight focus worlds describe the current direction. Applications are welcome globally; precise investment stages and geography remain subject to approved mandate records." image="/assets/odra-editorial-lavender.webp" actions={[{ label: "Meet the portfolio", href: "/portfolio" }, { label: "Founder support", href: "/founder-support" }]} />
    <section className="phase-section focus-worlds"><SectionHeading eyebrow="Focus areas" title="Four systems shaping what comes next." body="No portfolio allocation percentages are shown until their meaning and date basis are formally defined." /><div className="phase-focus-grid">{focusAreas.map((area) => <article className={`tone-${area.tone}`} key={area.number}><span>{area.number}</span><h3>{area.title}</h3><p>{area.body}</p><div>{area.tags.map((tag) => <small key={tag}>{tag}</small>)}</div></article>)}</div></section>
    <section className="phase-section fit-section"><div className="fit-intro"><p className="kicker">Founder-fit signals</p><h2>Evidence can arrive in more than one form.</h2><p>These are qualitative signals for a productive conversation, not a scorecard or promise of selection.</p></div><ol>{founderFitSignals.map((signal, index) => <li key={signal}><span>{String(index + 1).padStart(2, "0")}</span><p>{signal}</p></li>)}</ol></section>
    <section className="phase-section boundary-section"><SectionHeading eyebrow="Stage and geography" title="Open globally. Precise boundaries under review." /><div className="boundary-cards"><article><span>Confirmed</span><h3>Applications are welcome globally.</h3><p>This describes access to the application pathway, not a claim of global offices or investment in every jurisdiction.</p></article><article><span>Pending approval</span><h3>Stages, cheque language, and exclusions.</h3><p>These details will remain unpublished until the relevant investment mandate and operating policy are approved.</p></article></div><Disclosure>Odra does not infer investment eligibility from an applicant's location, sector label, or participation in a founder program.</Disclosure></section>
  </>;
}
